version: '3.8'
networks:
  nginx_default:
    external: true
  backend:
    driver: bridge

services:

  postgres:
    image: postgres:alpine
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    ports:
      - "5555:5432"
    networks:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    expose:
      - "8000"
    env_file:
      - ./backend/.env
    networks:
      - backend

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_BACKEND_URL=/api
    networks:
      - nginx_default
      - backend


volumes:
  postgres_data: