version: '3.8'
networks:
  backend_network:
    driver: bridge

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    expose:
      - "8000"
    env_file:
      - ./backend/.env
    networks:
      - backend_network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    environment:
      - REACT_APP_BACKEND_URL=/api
    networks:
      - backend_network

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend_network
